markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: joezxy's Blog
description: joezxy's Blog, powered by Jekyll...
feed: http://joezxy.github.io/atom.xml

author: joezxy

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
